### ISSUE TITLE
Shift legend to x-axis in Chart

### ISSUE THREAD

**Issue by lxu213** [HopkinsIDD/covid-dashboard-app#33]

**Comment by veev** [comment]
I believe this has been addressed in the most recent changes pushed to the refactor branch

**Comment by lxu213** [comment]
Great, it looks good - a few comments:
- Do we still need the scenario legend? It seems redundant at this point. 
- The font is pretty small, was that to make sure it's on the same line? I imagine one day we'll have longer scenario names. What are your thoughts on putting them on an axis instead of decreasing font size? Alternatively (or in addition), we should add some text wrapping for when the scenario names get unwieldy. 
- Removing the scenario legend can also help free up more room vertically for the graphs. Perhaps we could shift the confidence bounds legend inside the chart, similar to Graph - thoughts?

**Comment by veev** [comment]
It might be helpful to have test data with longer scenario names, as this may break formatting in other areas, or we may want to create rules where we shorten the names, as we did to arrive at how we are currently naming the longer names from the CA report. But I can definitely increase the font-size or style it as the current highlighted legend is. I can implement some text wrapping code to ensure that happens for axes as well.

I think removing the highlighting scenario legend makes sense in light of the x-axis. We can put the conf bounds legend in the chart like you suggest, but this may look a bit strange for the lower graph, since we'll need to make space for it but I don't think it makes sense to replicate across the three graphs. keeping it above may look cleaner. We could make a flex container so that it would be on the same line level as the callout that gets revealed on hover.

**Comment by lxu213** [comment]
https://github.com/HopkinsIDD/covid-dashboard-app/tree/longer-names branch now has test data with longer scenario names. I made a separate branch for this so we can play around with the text-wrapping rules and styling, particularly for Chart.

**Comment by veev** [comment]
There is progress on text wrapping on the `longer-names` branch. However, there is a strange issue where the text is only wrapping when the component mounts, not after update. I need to revisit when I have more time, so alternatives might be to character limit Scenario names for now...

**Comment by lxu213** [comment]
Resolved by https://github.com/HopkinsIDD/covid-dashboard-app/commit/c2f0677e508ed553ab4105da1b441b47efcbf448
